name: Renovate status

on:
  pull_request:
    branches:
      - master

jobs:
  renovate-status-check:
    if: ${{contains(github.head_ref, 'renovate')}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Packages
        run: npm i
      - name: Build Packages
        run: npm run build
      - name: Run test
        run: npm run test


